# Generated by Django 2.1.2 on 2019-04-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profesor', '__first__'),
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(blank=True, choices=[('1er Semestre', '1er Semestre'), ('2do Semestre', '2do Semestre')], max_length=50, null=True)),
                ('anio_cursado', models.CharField(blank=True, max_length=4)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Retiro', 'Retiro')], max_length=300)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ('anio_cursado', 'estado'),
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('sigla', models.CharField(max_length=10)),
                ('creditos', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Optativo', 'Optativo'), ('Obligatorio', 'Obligatorio')], max_length=12)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('nombre', 'sigla', 'creditos'),
            },
        ),
        migrations.CreateModel(
            name='Detalle_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_cursado', models.CharField(blank=True, max_length=4)),
                ('semestre', models.CharField(blank=True, max_length=2)),
                ('paralelo', models.IntegerField()),
                ('aprobados', models.CharField(blank=True, max_length=300, null=True)),
                ('rechazados', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('inscritos', models.CharField(blank=True, max_length=500, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Cursos')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'ordering': ('anio_cursado', 'semestre', 'curso'),
            },
        ),
        migrations.CreateModel(
            name='Lista_alumnos',
            fields=[
                ('id_lista', models.BigAutoField(primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ('id_lista', 'alumno'),
            },
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='lista_alumnos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Lista_alumnos'),
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profesor.Profesor'),
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='curso',
            field=models.ManyToManyField(blank=True, to='Cursos.Cursos'),
        ),
    ]
