# Generated by Django 2.1.2 on 2019-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0009_auto_20190605_1732'),
        ('Cursos', '0002_auto_20190511_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista_alumnos',
            options={},
        ),
        migrations.RemoveField(
            model_name='lista_alumnos',
            name='alumno',
        ),
        migrations.AddField(
            model_name='lista_alumnos',
            name='alumno',
            field=models.ManyToManyField(blank=True, to='Alumno.Alumno'),
        ),
    ]
