# Generated by Django 2.1.2 on 2019-06-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_auto_20190606_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='curso_en_malla',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Antigua', 'Antigua')], default='Nueva', max_length=40),
        ),
    ]
