# Generated by Django 2.1.2 on 2019-07-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_auto_20190606_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='nivelacion1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='nivelacion2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='semestre1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='semestre2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='semestre3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Cursos')),
            ],
        ),
        migrations.RemoveField(
            model_name='avancecurricular',
            name='curso',
        ),
    ]
