# Generated by Django 2.1.2 on 2019-07-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_auto_20190702_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancecurricular',
            name='nivelacion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.nivelacion1'),
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='nivelacion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.nivelacion2'),
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='semestre1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.semestre1'),
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='semestre2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.semestre2'),
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='semestre3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.semestre3'),
        ),
    ]
