# Generated by Django 2.1.2 on 2019-07-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0009_auto_20190704_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancecurricular',
            name='semestre1',
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='semestre1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.semestre1'),
        ),
        migrations.RemoveField(
            model_name='avancecurricular',
            name='semestre2',
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='semestre2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.semestre2'),
        ),
        migrations.RemoveField(
            model_name='avancecurricular',
            name='semestre3',
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='semestre3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.semestre3'),
        ),
        migrations.RemoveField(
            model_name='avancecurricular',
            name='trimestral',
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='trimestral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.trimestral'),
        ),
        migrations.RemoveField(
            model_name='semestre1',
            name='curso',
        ),
        migrations.AddField(
            model_name='semestre1',
            name='curso',
            field=models.ManyToManyField(blank=True, to='Cursos.Cursos'),
        ),
        migrations.RemoveField(
            model_name='semestre2',
            name='curso',
        ),
        migrations.AddField(
            model_name='semestre2',
            name='curso',
            field=models.ManyToManyField(blank=True, to='Cursos.Cursos'),
        ),
        migrations.RemoveField(
            model_name='semestre3',
            name='curso',
        ),
        migrations.AddField(
            model_name='semestre3',
            name='curso',
            field=models.ManyToManyField(blank=True, to='Cursos.Cursos'),
        ),
        migrations.RemoveField(
            model_name='trimestral',
            name='curso',
        ),
        migrations.AddField(
            model_name='trimestral',
            name='curso',
            field=models.ManyToManyField(blank=True, to='Cursos.Cursos'),
        ),
    ]
