# Generated by Django 2.1.2 on 2019-04-29 18:48

import Alumno.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Direccion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido_pat', models.CharField(max_length=30)),
                ('apellido_mat', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=13, validators=[Alumno.validators.digito_verificador])),
                ('telefono', models.CharField(max_length=12, null=True)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('mail', models.EmailField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id_beca', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.CharField(max_length=9)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos_homologados',
            fields=[
                ('id_curso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'Cursos_homologado',
                'verbose_name_plural': 'Cursos_homologados',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='DireccionAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=300, null=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Direccion.Comuna')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Direccion.Provincia')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Direccion.Region')),
            ],
            options={
                'verbose_name': 'Direccion_alumno',
                'verbose_name_plural': 'Direcciones_alumnos',
                'ordering': ('region', 'provincia', 'comuna'),
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pag', models.DateField()),
                ('monto', models.IntegerField()),
                ('tipo_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Cheque', 'Cheque'), ('Credito', 'Credito'), ('Debito', 'Debito')], max_length=30)),
                ('banco', models.CharField(max_length=50, null=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('fecha_pag', 'alumno'),
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_post', models.DateField()),
                ('universidad_procedencia', models.CharField(max_length=100)),
                ('carrera_procedencia', models.CharField(max_length=100)),
                ('nivelacion', models.CharField(choices=[('Necesita', 'Necesita'), ('No necesita', 'No necesita')], max_length=30)),
                ('semestre_ingreso', models.CharField(blank=True, max_length=30, null=True)),
                ('anio_ingreso', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_matricula', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20, null=True)),
                ('antecedentes_academicos', models.IntegerField(null=True)),
                ('antecedentes_profesionales', models.IntegerField(null=True)),
                ('carta_recomendacion', models.IntegerField(null=True)),
                ('entrevista', models.CharField(max_length=30, null=True)),
                ('puntaje', models.IntegerField(null=True)),
                ('resultados_condicion', models.CharField(choices=[('Aprueba', 'Aprueba'), ('Reprueba', 'Reprueba')], max_length=30)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'Postulacion',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ('fecha_post',),
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='becas',
            field=models.ManyToManyField(blank=True, to='Alumno.Becas'),
        ),
    ]
