# Generated by Django 2.1.2 on 2019-05-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_auto_20190429_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('id_cobro', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Vencido', 'Vencido'), ('Pendiente', 'Pendiente')], max_length=30)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.IntegerField()),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
        ),
    ]
