# Generated by Django 2.1.2 on 2019-05-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0005_auto_20190513_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cobros',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Matricula'),
        ),
    ]
