# Generated by Django 2.1.2 on 2019-05-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0006_auto_20190513_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Matriculado', 'Matriculado'), ('Postulante', 'Postulante'), ('En Espera', 'En Espera')], max_length=300, null=True),
        ),
    ]
