# Generated by Django 2.1.2 on 2019-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0007_alumno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Matriculado', 'Matriculado'), ('Postulante', 'Postulante'), ('En Espera', 'En Espera'), ('Rechazado', 'Rechazado')], max_length=300, null=True),
        ),
    ]
