# Generated by Django 2.1.2 on 2019-06-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0008_auto_20190603_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becas',
            name='tipo',
            field=models.CharField(choices=[('Continuidad de Estudios', 'Continuidad de Estudios'), ('Alumno Destacado', 'Alumno Destacado'), ('Alumni PUCV', 'Alumni PUCV')], max_length=100),
        ),
    ]
