# Generated by Django 2.1.2 on 2019-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0009_auto_20190605_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(default='Chilena', max_length=300),
        ),
    ]
