# Generated by Django 2.1.2 on 2019-07-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0010_alumno_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='anio_ingreso',
            field=models.IntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='alumno',
            name='semestre_ingreso',
            field=models.CharField(blank=True, choices=[('Primer Semestre', 'Primer Semestre'), ('Segundo Semestre', 'Segundo Semestre'), ('Primer Trimestre', 'Primer Trimestre'), ('Segundo Trimestre', 'Segundo Trimestre'), ('Tercer Trimestre', 'Tercer Trimestre'), ('Cuarto Trimeste', 'Cuarto Trimestre')], max_length=300, null=True),
        ),
    ]
