# Generated by Django 2.1.2 on 2019-06-07 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_build', models.CharField(max_length=255)),
                ('Ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fechaInicio', models.DateField(verbose_name='%d-%m-%Y')),
                ('fechaTermino', models.DateField(blank=True, null=True, verbose_name='%d-%m-%Y')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Calendario.Edificio')),
                ('estadoTarea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Calendario.EstadoTarea')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Calendario.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipoTarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Calendario.TipoTarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
