# Generated by Django 2.1.2 on 2019-07-16 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0009_auto_20190605_1732'),
        ('Titulacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno_en_Titulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=13)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.Alumno_en_Titulacion')),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=None)),
                ('tipo', models.CharField(blank=True, choices=[('Primera Entrega', 'Primera Entrega'), ('Segunda Entrega', 'Segunda Entrega')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profeExaminador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=13)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titulacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno_en_titulo',
            name='avance',
        ),
        migrations.RemoveField(
            model_name='alumno_en_titulo',
            name='entreegafinal',
        ),
        migrations.RemoveField(
            model_name='alumno_en_titulo',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='alumno_en_titulo',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='alumno_en_titulo',
            name='fk_idcomite',
        ),
        migrations.RemoveField(
            model_name='avancetesis',
            name='fk_entregaTesis',
        ),
        migrations.RemoveField(
            model_name='entregatesis',
            name='fk_Tesis',
        ),
        migrations.RemoveField(
            model_name='entregatesisfinal',
            name='fk_entregaTesis',
        ),
        migrations.RemoveField(
            model_name='estado_actual',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='estado_anterior',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='tr_alumno_titulo',
            name='fk_alumtitu',
        ),
        migrations.RemoveField(
            model_name='tr_alumno_titulo',
            name='fk_idalumno',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='Director_Tesis',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='Prof_examinador',
        ),
        migrations.AddField(
            model_name='comite',
            name='rol',
            field=models.CharField(choices=[('Correferente', 'Correferente'), ('Externo', 'Externo'), ('Interno', 'Interno'), ('Director', 'Director')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='valido',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Alumno_en_titulo',
        ),
        migrations.DeleteModel(
            name='avanceTesis',
        ),
        migrations.DeleteModel(
            name='director_tesis',
        ),
        migrations.DeleteModel(
            name='EntregaTesis',
        ),
        migrations.DeleteModel(
            name='EntregaTesisFinal',
        ),
        migrations.DeleteModel(
            name='Estado_Actual',
        ),
        migrations.DeleteModel(
            name='Estado_Anterior',
        ),
        migrations.DeleteModel(
            name='ProfExaminador',
        ),
        migrations.DeleteModel(
            name='Tesis',
        ),
        migrations.DeleteModel(
            name='tr_Alumno_titulo',
        ),
        migrations.AddField(
            model_name='detalle',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.estado'),
        ),
        migrations.AddField(
            model_name='comite',
            name='alumnoTitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.Alumno_en_Titulacion'),
        ),
        migrations.AddField(
            model_name='comite',
            name='profeExaminador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.profeExaminador'),
        ),
    ]
