# Generated by Django 2.1.2 on 2019-07-29 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0003_auto_20190729_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.estado'),
        ),
    ]
