# Generated by Django 2.1.2 on 2019-08-04 06:05

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0011_auto_20190729_1739'),
        ('Titulacion', '0006_auto_20190803_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.estado'),
        ),
        migrations.RemoveField(
            model_name='titulacion',
            name='alumno',
        ),
        migrations.AddField(
            model_name='titulacion',
            name='alumno',
            field=models.ManyToManyField(blank=True, default=builtins.all, to='Alumno.Alumno'),
        ),
    ]
