# Generated by Django 2.1.2 on 2019-08-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0007_auto_20190804_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.estado'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='alumno',
            field=models.ManyToManyField(blank=True, to='Alumno.Alumno'),
        ),
    ]
