# Generated by Django 2.1.2 on 2019-08-04 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0008_auto_20190804_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='enviar_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('mensaje', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='detalle',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.estado'),
        ),
    ]
