# Generated by Django 2.1.2 on 2019-08-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Titulacion', '0011_auto_20190804_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.Alumno_en_Titulacion'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Titulacion.estado'),
        ),
    ]
