# Generated by Django 2.1.2 on 2019-04-29 18:52

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionprofesor',
            name='comuna',
            field=smart_selects.db_fields.GroupedForeignKey(default=1, group_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='Direccion.Comuna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccionprofesor',
            name='provincia',
            field=smart_selects.db_fields.GroupedForeignKey(default=2, group_field='region', on_delete=django.db.models.deletion.CASCADE, to='Direccion.Provincia'),
            preserve_default=False,
        ),
    ]
